version: '3.4'

services: 
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - 5672:5672
    #  - 15672:15672    
    #network_mode: host
    volumes: 
      - rabbitmq:/var/lib/rabbitmq

  consul:
    image: consul
    container_name: consul
    ports:
      - 8500:8500
    #networks:
    #  - dshop
    # network_mode: host
    volumes:
      - consul:/consul/data

  fabio:
    image: fabiolb/fabio
    container_name: fabio
    environment:
    - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
    #networks:
    #  - dshop
    # network_mode: host
    ports:
    - 9998:9998
    - 9999:9999

  vault:
    image: vault
    container_name: vault
    ports:
      - 8200:8200
    #networks:
    #  - dshop
    # network_mode: host
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=secret
    cap_add:
      - IPC_LOCK

  postgis:
    image: postgis/postgis:12-master
    ports:
      - 5432:5432
    restart: always
    environment: 
      POSTGRES_PASSWORD: example
  admin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8888:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@mail.ua
      - PGADMIN_DEFAULT_PASSWORD=example

  redis:
    image: redis:latest
    ports:
      - 6379:6379 

  vault:
    image: vault
    container_name: vault
    ports:
      - 8200:8200
    #networks:
    #  - dshop
    # network_mode: host
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=secret
    cap_add:
      - IPC_LOCK

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    container_name: elasticsearch
    networks:
      - eco-shop
      
  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.3
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - eco-shop

volumes:
  consul:
    driver: local
  rabbitmq:
    driver: local  

networks:
  eco-shop:

